package plausibcheck.adress

import org.apframework.drools.simple.boot.model.Address;
import org.apframework.drools.simple.boot.model.fact.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：校验通过!");
end

rule "Postcode should be filled"
    when
        address : Address(postcode != null)
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：规则执行！");
end